# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytdui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(250, 40, 711, 121))
        self.label.setStyleSheet("font: 24pt \"Reem Kufi\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(260, 250, 481, 231))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"background-color: rgb(207, 0, 0);}")
        self.widget_2.setObjectName("widget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 70, 391, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setEnabled(True)
        self.widget_3.setGeometry(QtCore.QRect(40, 120, 401, 80))
        self.widget_3.setObjectName("widget_3")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 361, 31))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 381, 71))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(190, 100, 75, 23))
        self.pushButton.setStyleSheet("font: 8pt \"Reem Kufi\";\n"
"background-color: rgb(148, 0, 0);\n"
"color: white;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 250, 171, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 201, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 211, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(20, 380, 201, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 340, 201, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 280, 201, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Reem Kufi\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Youtube Downloader by MonCcciii"))
        self.label_8.setText(_translate("MainWindow", ""))
        self.label_9.setText(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "Enter :)"))
        self.label_2.setText(_translate("MainWindow", "How To Use?"))
        self.label_4.setText(_translate("MainWindow", "2. Press Enter"))
        self.label_6.setText(_translate("MainWindow", "into the Downloads folder of the folder"))
        self.label_7.setText(_translate("MainWindow", "this file is in."))
        self.label_5.setText(_translate("MainWindow", "3. Enjoy! Video should be downloaded"))
        self.label_3.setText(_translate("MainWindow", "1. Input link into textbox."))
